### ISSUE TITLE
Add copyTree and renameKey

### ISSUE THREAD

**Issue by m417z** [simonbuchan/native-reg#20]
`copyTree` can be implemented with [RegCopyTreeW](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regcopytreew), and `renameKey` can be implemented with `RegRenameKey`. Both functions are available since Windows Vista, and the wrapper should be straightforward.

`RegRenameKey` is [not documented](https://github.com/MicrosoftDocs/sdk-api/pull/710), but the function exists, unchanged, since Windows Vista, and is declared in the SDK headers. For such a basic operation, I think that it's worth using an undocumented function.

**Comment by simonbuchan** [comment]
I'm a bit dubious about adding a binary dependency on undocumented functions, even if well known and declared in the headers. It smells of the actually internal, but court-ordered documented functions that you absolutely shouldn't use (mostly because they suck), but the real issue is that since it's compiled in you can't choose *not* to have that dependency, and I don't want to force that on people. Possibly the bigger issue is the semantic effect (e.g. key watches moving with the key!) may not be expected by some software. I don't officially have a minimum windows version, but requiring Vista seems fine enough (I still occasionally see a requirement for 7), and I probably already have that as a dependency anyway.

copyTree seems to mostly be a missed case, that at least is very uncontroversial (other than being added in Vista, as mentioned above). When I get some time, I'll look at this one at leats.

**Comment by m417z** [comment]
Guess what, [it is documented now](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regrenamekey)! :)

Turns out that [Node dropped support for XP and Vista in v6.0.0 (2016)](https://stackoverflow.com/a/40869223), so I believe it's fine.

Regarding key watches moving with the key, I can't think of a problematic case for that. It should have the same effect as renaming a key with regedit.

**Comment by simonbuchan** [comment]
Wow, that was fast!

**Comment by simonbuchan** [comment]
Could you check out v0.3.5 in `@next` to let me know if this is good? I've got a few too many changes for me to be happy with an 11:30PM release to `@latest` 😊

**Comment by m417z** [comment]
I tried `renameKey` and it seems to be working as expected.
