### ISSUE TITLE
Gracefully "Building" on macOS

### ISSUE THREAD

**Issue by semireg** [simonbuchan/native-reg#23]
Yes, I know this module is for windows... 😄 

My Electron app runs on both Windows/Mac. I use [node-machine-id](https://github.com/automation-stack/node-machine-id) for powering my app's licensing. One of the forks uses `native-reg` and it works great on Windows. However, it breaks the macOS builds. Is there a way to add a no-op in the build process for non-Windows platforms?

Reference: https://github.com/automation-stack/node-machine-id/issues/56#issuecomment-885660516

```
> App@2.3.6 electron-rebuild ~/app
> node -r ../internals/scripts/BabelRegister.js ../internals/scripts/ElectronRebuild.js

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'node-addon-api'
Require stack:
- ~/app/node_modules/native-reg/[eval] <---- **native-reg**
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:116:20)
    at Object.runInThisContext (vm.js:306:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at evalScript (internal/process/execution.js:80:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    ‘~/app/node_modules/native-reg/[eval]'
  ]
}
gyp: Call to 'node -p "require('node-addon-api').gyp"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
```

**Comment by simonbuchan** [comment]
The assumption is that you would do something like:

```js
let reg;
if (process.platform === "win32") {
  reg = require("reg");
}
```

But just being a no-op is much nicer - it's just tricky to get right when there is probably some unknown bundler in play. My tray icon package was recently fixed by a nicely done user PR to do that, I'll look at doing that here.

The actual issue though, is that `electron-rebuild` is ignoring the `gypfile: false` in the package.json and [just checking for `binding.gyp`](https://github.com/electron/electron-rebuild/blob/19147cc8dae3acd2d329f7526b389a728907679d/src/rebuild.ts#L243), so I need to remove that from the bundled package. It's a bit annoying, as I liked having the "nothing up my sleeve" here's how this was built included, but I think I can just not have it in the default location.

**Comment by simonbuchan** [comment]
My mistake, it was actually this one! So the only thing is moving the gypfile....

**Comment by simonbuchan** [comment]
Give this a try in @next / 0.3.6 - if it's all good i'll release it to `latest`.
