### ISSUE TITLE
"No native build was found for platform..." when running in electron

### ISSUE THREAD

**Issue by KSneijders** [simonbuchan/native-reg#40]
Hey! 

First of all, thanks for this package- it's awesome! 

I am in the process of replacing an older project with a [newer electron template](https://github.com/umbrella22/electron-vite-template).
I'm relatively inexperienced in the world of building the binaries so this might be a noob question. 

But I'm getting the following error after running `npm run dev` (`tsx .electron-vite/dev-runner.ts`).

```
  Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=121 uv=1 libc=glibc node=20.9.0 electron=29.1.6
      loaded from: C:\Users\_USER_\Documents\Projects\Electron\electron-vite-template\dist\electron

      at load.resolve.load.path (C:\Users\_USER_\Documents\Projects\Electron\electron-vite-template\dist\electron\main\main.js:19874:10)
      at load (C:\Users\_USER_\Documents\Projects\Electron\electron-vite-template\dist\electron\main\main.js:19836:31)
      at C:\Users\_USER_\Documents\Projects\Electron\electron-vite-template\dist\electron\main\main.js:20050:49
      at Object.<anonymous> (C:\Users\_USER_\Documents\Projects\Electron\electron-vite-template\dist\electron\main\main.js:20374:3)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
      at Module.load (node:internal/modules/cjs/loader:1098:32)
      at Module._load (node:internal/modules/cjs/loader:945:12)
      at c._load (node:electron/js2c/node_init:2:13672)
      at cjsLoader (node:internal/modules/esm/translators:288:17)
```

I've looked at the other issues in this project and as far as I can tell this package has a feature to fallback on building the binary if it cannot find any. What are the things I can do/check to solve this?

Like I said, this issue is out of my league but would love to know how to get started. Any help is appreciated!   
Thanks in advance 🙂

**Comment by simonbuchan** [comment]
Hmm. In theory, it should never need a build as I use N-API, which is a stable binary interface that should work for any version of node or electron...

My best guess here, given that's a JavaScript stack, is that your bundler configuration isn't putting the binary .node file in the right place? It's been forever since I've touched this, so I'm not sure exactly, but it should only need to be copied to the output/distribution directory for builds, I'm less sure about what vite dev would expect....

If you don't figure out before I get to it, I should have time to check this out in the next week or so. Feel free to poke me if I forget though! 😅

**Comment by KSneijders** [comment]
Thanks for the quick response! I've been trying some things but don't have much progress. As you can see I've relayed your question in the template repo as well hoping they could shed some light on it. 

I appreciate all the help you can give. I've tried [another vite template](https://github.com/Deluze/electron-vue-template) which is a lot simpler and there it works flawlessly. 

Both use different methods of launching the dev environment (first using tsx and the latter using node itself).

**Comment by KSneijders** [comment]
@simonbuchan Hey, due to the necessary velocity and deadlines for our project we tried another package for reading the registry.   
Which worked with both templates.  

So if I'm the only one who reported this issue, don't feel pressured to resolve the issue.  
That being said, if you do happen to look into it, I'd love to learn more about it!

Thanks again! ❤️ And I'm sorry for creating a now sort of redundant issue.

**Comment by KSneijders** [comment]
Alright, will be closing the issue myself as apparently this is not an issue `native-reg` at all. 
It's a config option in the template I didn't know about. [See answer on the template repo](https://github.com/umbrella22/electron-vite-template/issues/131#issuecomment-2156054901).

**Comment by simonbuchan** [comment]
Hey, glad to see things worked out for you, no matter which approach you go with!

Yeah, build config is always a real pain, hopefully this at least helps others in the future if they have the same issue.

**Comment by simonbuchan** [comment]
Taking a look at that issue:

- yeah, adding this library as external would work and it's extremely easy, the only downside being that it might include unnecessary binaries (eg the ARM build when you're building an x86-64 binary), but I'd say it's not worth fiddling with given the size of the rest of electron. It's an easy thing to add to the readme though!

- node-winreg made me feel a bit icky when I was looking for a registry library, since it has to go through a command line. I don't know if it's still an issue now but I believe it had issues with Unicode as well at the time. But you pay a price for going with a native API, it's a lot more complicated. It's probably worth me covering the alternatives and the trade-offs too.

**Comment by KSneijders** [comment]
@simonbuchan I'd love to know the up and downsides between the libraries! I'm not too familiar with them or the registry itself, so usually, if it works, I'm happy.

Having a comparison sheet would, at least for me, be extremely useful to make a more educated decision!

**Comment by simonbuchan** [comment]
Just updated the readme with a bunch of comparisons and details and added an example with a couple of ways to bundle with rollup (and thus vite).

Hopefully this helps someone, even if you're already good.
